# Generated by Django 4.2.7 on 2024-02-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0002_job_delete_joblisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('employer_name', models.CharField(max_length=200)),
                ('job_city', models.CharField(max_length=200)),
                ('job_employment_type', models.CharField(max_length=200)),
                ('job_educational_level', models.JSONField()),
                ('job_min_salary', models.IntegerField()),
                ('job_max_salary', models.IntegerField()),
                ('job_posted_at_datetime_utc', models.DateTimeField()),
                ('job_description', models.TextField()),
                ('employer_website', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
    ]
